<?php

/**
 * @file
 * Contains examples demonstrating CTools Plugin API.
 */


module_load_include('inc', 'cto', 'includes/tools');

/**
 * Implements hook_menu().
 */
function ppg_menu() {
  $items = array();

  $items['ppg'] = array(
    'title' => 'Plugin API',
    'page callback' => 'ppg_pcb_main',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['ppg/list'] = array(
    'title' => 'List',
    'page callback' => 'ppg_pcb_list',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );

  return $items;
}


/**
 * Page callback: Plugin API menu.
 */
function ppg_pcb_main() {
  return t('Select CTools Plugin action from menu.');
}


/**
 * Page callback: Plugin API: ctools_get_plugins().
 */
function ppg_pcb_list() {
  ctools_include('plugins');
  $plugin_types = ctools_plugin_get_plugin_type_info();
  dpm($plugin_types, 'plugin_types');

  dpm('CTools');

  $plugins = ctools_get_plugins('ctools', 'access');
  dpm($plugins, 'type: access');

  $plugins = ctools_get_plugins('ctools', 'arguments');
  dpm($plugins, 'type: arguments');

  $plugins = ctools_get_plugins('ctools', 'cache');
  dpm($plugins, 'type: cache');

  $plugins = ctools_get_plugins('ctools', 'content_types');
  dpm($plugins, 'type: content_types');

  $plugins = ctools_get_plugins('ctools', 'contexts');
  dpm($plugins, 'type: contexts');

  $plugins = ctools_get_plugins('ctools', 'export_ui');
  dpm($plugins, 'type: export_ui');

  $plugins = ctools_get_plugins('ctools', 'relationships');
  dpm($plugins, 'type: relationships');

  dpm('CTools->Page manager');

  $plugins = ctools_get_plugins('page_manager', 'task_handlers');
  dpm($plugins, 'type: task_handlers');

  $plugins = ctools_get_plugins('page_manager', 'tasks');
  dpm($plugins, 'type: tasks');

  $plugins = ctools_get_plugins('page_manager', 'page_wizards');
  dpm($plugins, 'type: page_wizards');

  dpm('Panels');

  $plugins = ctools_get_plugins('panels', 'cache');
  dpm($plugins, 'type: cache');

  $plugins = ctools_get_plugins('panels', 'display_renderers');
  dpm($plugins, 'type: display_renderers');

  $plugins = ctools_get_plugins('panels', 'layouts');
  dpm($plugins, 'type: layouts');

  $plugins = ctools_get_plugins('panels', 'styles');
  dpm($plugins, 'type: styles');

  $core_modules = array('aggregator', 'block', 'blog', 'blogapi', 'book', 'color', 'comment', 'contact', 'drupal', 'filter', 'forum', 'help', 'legacy', 'locale', 'menu', 'node', 'path', 'ping', 'poll', 'profile', 'search', 'statistics', 'taxonomy', 'throttle', 'tracker', 'upload', 'user', 'watchdog', 'system');
  foreach($core_modules as $module) {
    $blocks[$module] = module_invoke($module, 'block_info');
  }

  dpm($blocks, 'blocks');

  return t('Done');
}
